spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing

#orintdb config
orient:
  database:
    url: remote:127.0.0.1/wesley
    user: root
    password: root123